#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import argparse
import re
import os
import tempfile
import shutil
import subprocess
from typing import Dict, List, Tuple, Union  # , Any, Callable
from subprocess import PIPE

def get_sources(folder: str) -> List[str]:
    file_list: List[str] = os.listdir(folder)
    s_list = []
    for file in file_list:
        if file.lower() == "readme.md":
            s_list.append(file)
        elif file.endswith(".tio"):
            s_list.append(file)
        elif file.endswith(".vpl"):
            s_list.append(file)
    return [os.path.join(folder, file) for file in s_list]

def get_solvers(folder: str) -> List[str]:
    file_list: List[str] = os.listdir(folder)
    s_list = []
    for file in file_list:
        if file.lower().startswith("solver"):
            s_list.append(file)
    return [os.path.join(folder, file) for file in s_list]

def prepare_exec(solver, folder):
    def prepare_c(solver: str) -> str:
        cmd = ["gcc", "-Wall", "-fsanitize=address", "-Wuninitialized", "-Wparentheses", "-Wreturn-type", "-Werror"]
        cmd += ["-fno-diagnostics-color", solver, "-o", solver + ".out", "-lm", "-lutil"]
        result = subprocess.run(cmd)
        if result.returncode != 0:
            exit(1)
        return solver + ".out"

    def prepare_cpp(solver: str) -> str:
        cmd = ["g++", "-std=c++17", "-Werror", "-Wshadow", "-Wall", "-g", "-fsanitize=address", "-fsanitize=undefined", "-D_GLIBCXX_DEBUG"]
        cmd += [solver, "-o", solver + ".out"]
        result = subprocess.run(cmd)
        if result.returncode != 0:
            exit(1)
        return solver + ".out"

    def prepare_hs(solver, folder) -> str:
        readme_path = os.path.join(folder, "Readme.md")
        if not os.path.isfile(readme_path):
            print(readme_path, " not found for haskell build")
            exit(1)
        main_hs =  "__Main.hs"
        tio_hs = "__t.tio"
        main_out = "__Main.hs.out"
        
        subprocess.run(["hsmod", folder, "--tio", tio_hs, "--main", main_hs])

        main_hs = os.path.join(folder, "__Main.hs")
        tio_hs = os.path.join(folder, "__t.tio")
        main_out = os.path.join(folder, "__Main.hs.out")

        # reading main only
        with open(main_hs, "r") as f:
            main_content = f.read()
        # reading solver
        with open(solver) as f:
            solver_content = f.read()
        # mounting full main
        with open(main_hs, "w") as f:
            f.write(solver_content + "\n" + main_content)
        # getting extracted texts
        with open(tio_hs) as f:
            tio_content = f.read()
        # inserting tio tests on readme
        with open(readme_path, "a") as f:
            f.write("\n" + tio_content)
        # compiling haskell exec
        subprocess.run(["ghc", main_hs, "-o", main_out])
        return main_out


    if solver.endswith(".py"):
        return "python3 " + solver
    elif solver.endswith(".js"):
        return "node " + solver
    elif solver.endswith(".c"):
        return prepare_c(solver)
    elif solver.endswith(".cpp"):
        return prepare_cpp(solver)
    elif solver.endswith(".hs"):
        return prepare_hs(solver, folder)
    else:
        print("  fail: solver not supported:", solver)

def test_folder(folder: str, vertical: bool):
    solver_list = get_solvers(folder) # [solver.c,solver.cpp,solver.js]
    source_list = get_sources(folder)
    fileonly = lambda x:  x.split(os.sep)[-1]

    print ("  src_list: [" + ", ".join(map(fileonly, source_list)) + "]")
    for solver in solver_list:
        exec_cmd = prepare_exec(solver, folder)
        vert = ["-v"] if vertical else []
        param = ["th", "run"] + [exec_cmd] + source_list + vert
        solver_name = "solver: " + fileonly(solver)
        try:
            p = subprocess.Popen(param, stdout=PIPE, stderr=PIPE, universal_newlines=True)
            stdout, stderr = p.communicate()
            if p.returncode == 0:
                print("  ✓ " + solver_name)
            else:
                print("  🞩 " + solver_name)
                print(stdout)
                print(stderr)
                print("  🞩 " + solver_name)
                return False
        except Exception as e:
            print(str(e))
            return False
    return True
        
def copy_to_temp(folder):
    temp_dir = tempfile.mkdtemp()
    for file in os.listdir(folder):
        if os.path.isfile(os.path.join(folder, file)):
            shutil.copyfile(os.path.join(folder, file), os.path.join(temp_dir, file))
    return temp_dir

def main():
    parser = argparse.ArgumentParser(prog='htest', description="testador de código", formatter_class=argparse.RawTextHelpFormatter)
    parser.add_argument('folders', type=str, nargs="*", help='pasta com os dados')
    parser.add_argument('--vertical', '-v', action='store_true', help="vertical diff")
#    parser.add_argument('--main', '-m', action='store', type=str, help="arquivo para salvar a main")
#    parser.add_argument("--update", action='store_true', help="Update main inside Readme")
    args = parser.parse_args()

    if len(args.folders) == 0:
        folders = ["."]
    if args.folders:
        folders = args.folders
    for folder in folders:
        if not os.path.isdir(folder):
            continue
        if len(get_sources(folder)) == 0:
            print("  fail: test sources not found in this folder")
            exit(1)
        temp_dir = copy_to_temp(folder)
        print(folder)
        print("  temp_dir:", temp_dir)
        if not test_folder(temp_dir, args.vertical):
            print("  fail:", folder)
            exit(1)


if __name__ == '__main__':
    main()


